env:
  browser: true
  commonjs: true
  es6: true
  node: true
extends: airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  no-use-before-define:
    - error
    - {functions: false, classes: true, variables: false}
  no-param-reassign:
    - 2
    - {props: false}
  no-underscore-dangle: 0